# SEE: https://lithic.tech/blog/2020-05/makefile-dot-env
ifneq (,$(wildcard ./.env))
    include .env
    export
endif

build:
	go build -o server

build-d:
	GOOS=linux GOARCH=amd64 CGO_ENABLED=1 CC=/usr/local/bin/x86_64-linux-musl-cc go build --ldflags='-linkmode external -extldflags "-static" -w -s' -o ./data/new_server .

deploy-d:
	docker-compose exec app bash -c "mv ./data/new_server ./server && /opt/work/restart.sh"

diff:
	pushd ./infrastructure && cdk diff "*Stack" --profile xxx && popd

deploy:
	pushd ./infrastructure && cdk deploy "*Stack" --profile xxx && popd

synth:
	pushd ./infrastructure && cdk synth "*Stack" --profile xxx && popd

destroy:
	pushd ./infrastructure && cdk destroy "*Stack" --profile xxx && popd

ecr-push:
  docker-compose build
	./infrastructure/bin/ecr-deploy.sh --profile xxx -e prod -t "${APP_IMAGE_TAG}" -i play-with-litestream_app
